### ISSUE TITLE
my wife left me while i was studying your code

### ISSUE THREAD

**Issue by TommyB123** [Sp4zzy/DDRoller#2]
i demand a refund .

**Comment by Sp4zzy** [comment]
but it's free

**Comment by frostgaming** [comment]
Weird, I got a wife. Do you live in Texas by chance?

**Comment by TommyB123** [comment]
yes

**Comment by frostgaming** [comment]
> it

> wasnt

`me`

### i swear

**Comment by Sp4zzy** [comment]
Closing because this code SUCKS, DON'T DO IT.
